# Generated by Django 4.0.4 on 2022-04-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_long', models.CharField(max_length=500)),
                ('url_custom', models.CharField(max_length=20)),
            ],
        ),
    ]
