# Generated by Django 4.0.4 on 2022-05-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url_custom',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
