# Generated by Django 4.0.4 on 2022-07-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0002_alter_url_url_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url_long',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
