# Generated by Django 4.0.4 on 2023-03-11 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0003_alter_url_url_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='click',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='url',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
